config/routes.rb
# -*- encoding : utf-8 -*-
#
Yarb::Application.routes.draw do

  root 'landings#index'

  match 'set_locale/:locale' => 'application#set_locale',      via: 'GET',  as: 'set_locale'

  match 'sign_in'            => 'session#new',                 via: 'GET',  as: 'sign_in'
  match 'sign_in'            => 'session#create',              via: 'POST', as: 'create_session'
  match 'sign_out'           => 'session#delete',              via: 'GET',  as: 'sign_out'
  match 'forgot_password'    => 'session#forgot_password',     via: 'GET',  as: 'forgot_password'
  match 'reset_password'     => 'session#reset_password',      via: 'POST', as: 'reset_password'

  match 'sign_up'            => 'sign_up#new',                 via: 'GET',  as: 'sign_up'
  match 'sign_ups'           => 'sign_up#create',              via: 'POST', as: 'sign_ups'
  match 'sign_up/accept_invitation/:token' => 'sign_up#accept_invitation', via: 'GET', as: 'accept_sign_up_invitation'

  match '/auth/:provider/callback' => 'session#create',        via: 'GET'
  match '/auth/identity/register'  => 'users#create',          via: 'POST'
  match '/auth/failure'            => 'session#failure',       via: 'GET'
  match '/sign_up/complete_auth'   => 'session#complete_auth', via: 'POST'

  match 'confirm_email/:token' => 'email_confirmation#confirm', via: 'GET', as: 'confirm_email'

  match 'users/:token/edit_password' => 'users#edit_password', via: 'GET', as: 'edit_password_users'
  match 'users/:token/update_password' => 'users#update_password', via: 'POST', as: 'update_password_users'

  resources :users
  resources :sign_up_invitations, only: [:index, :new, :create, :destroy]


  resources :pages do
    collection do
      post 'update_order'
    end
  end

end

app/controllers/session_controller.rb
# -*- encoding : utf-8 -*-
#
require "oauth_sign_up"

# The SessionController handles log-in and log-out
# by setting a valid's user-id to session[:user_id]
class SessionController < ApplicationController

  # GET /sign_in
  def new
  end

  # POST /sign_in
  def create
    if @auth = request.env["omniauth.auth"]
      create_with_omniauth
    else
      create_with_identity
    end
  end

  # POST /sign_up/complete_auth
  def complete_auth
    user = create_and_sign_in_user_with_authentication
    if user
      redirect_to root_path,
        notice: t(:successfully_logged_in_as, user: user.name).html_safe
    else
      redirect_to root_path, alert: t("sign_up.can_not_create_user")
    end
  end


  # DELETE /sign_out
  def delete
    session.destroy
    redirect_to root_path, notice: t(:successfully_signed_out)
  end


  # GET /auth/failure?message=invalid_credentials
  def failure
    flash[:alert] = t("sign_in_view.oauth_failed",
                      message: t(params[:message].to_sym)
                     ).html_safe
    render :new, status: :unauthorized
  end

  # GET /forgot_password
  def forgot_password
  end

  # POST /reset_password
  def reset_password
    _user = User.find_by(:email, extract_email_from_params(params['/reset_password']))

    if _user
      _user.create_edit_token!
      redirect_to sign_in_path, notice: t('passwort_reset')
    else
      redirect_to sign_in_path
    end

  end

  private

  def create_with_identity
    email, password = extract_params(params["/sign_in"])
    user = User.find_by( :email, email ) || NilUser.new
    authenticate_and_redirect(user, password)
  end

  def create_with_omniauth
    user = AuthenticationService.new(self,@auth,session).user
    valid_user?(user) ?  created_successfully(user) : create_failed(user)
  end

  def create_failed user
    user.delete if user
    @sign_up = OAuthSignUp.new(@auth,session)
    render :complete_auth
  end

  def created_successfully user
    session[:user_id] = user.id
    redirect_to root_path, notice: t("successfully_logged_in_as", user: user.name).html_safe
  end

  def create_and_sign_in_user_with_authentication
    if allowed_without_or_valid_invitation?
      create_and_sign_in_user *extract_oauth_params(params[:o_auth_sign_up])
    end
  end

  def create_and_sign_in_user email, name, provider, uid
    user = User.create! email: email, name: name
    user.recreate_authentication provider, uid
    session[:user_id] = user.id
    ApplicationHelper.invitation_service_for(user,params[:o_auth_sign_up])
    user
  end

  def extract_params _params
    [ _params.fetch(:email), _params.fetch(:password) ]
  end

  def extract_email_from_params _params
    _params.fetch(:email)
  end

  def extract_oauth_params hash
    [ hash[:email], hash[:name], hash[:provider], hash[:uid] ]
  end

  def authenticate_and_redirect(user, password)
    user.authenticate(password) ?  assign_session(user) : render_new_with_error
  rescue
    render_new_with_error
  end

  private

  def valid_user? user
    user && user.valid?
  end

  def assign_session user
    session[:user_id] = user.id
    redirect_to root_path,
      notice: t(:successfully_logged_in_as, user: user.name).html_safe
  end

  def render_new_with_error
    flash.now[:error] = t(:invalid_credentials)
    render :new
  end

  def allowed_without_or_valid_invitation?
    !ApplicationHelper.needs_invitation? ||
      ApplicationHelper.find_invitation(params[:o_auth_sign_up])
  end

end

app/views/session/_session_nav.haml
- if signed_in?
  %li= link_to "<strong>#{current_user.name}</strong>".html_safe, user_path(current_user), title: current_user.roles.map(&:to_s).join(', ')
  %li= link_to t(:sign_out), sign_out_path
- else
  %li{class: current_page?(sign_up_path) ? 'active':''}= link_to t("sign_up.label"), sign_up_path
  %li{class: current_page?(sign_in_path) ? 'active':''}= link_to t(:sign_in), sign_in_path

app/views/session/complete_auth.haml
.row
  .span6.offset3
    #sign-up-form.gap-top.gap-bottom

      %h1= t("sign_up.welcome")
      %h2= t("sign_up.sign_up_with", provider: t("providers.#{@sign_up.provider}"))

      = render_errors_for @sign_up
      = simple_form_for @sign_up, url: "/sign_up/complete_auth", html: { class: 'form-horizontal'} do |f|
        %fieldset
          = f.input :provider, as: :hidden
          = f.input :uid, as: :hidden
          = f.input :name, label: t("sign_up.name")
          = f.input :email, as: 'email',
            label: t("sign_up.email")
          = f.input :invitation_token if ApplicationHelper.needs_invitation?

        .form-actions
          = f.submit t("sign_up.register_button"), class: 'btn btn-primary'

.row
  %p &nbsp;

app/views/session/forgot_password.haml
#sign-in.row
  .span7.offset2
    = simple_form_for reset_password_path, url: '/reset_password',
      html: { class: 'form-horizontal'} do |f|
      %fieldset
        = f.input :email, label: t(:email), as: 'email'
      .form-actions
        = f.submit t(:reset_password), class: 'btn btn-danger'
.row
  %p &nbsp;

app/views/session/new.haml
#sign-in.row
  .span7.offset2
    .gap-top.gap-bottom
      %h1=t(:sign_in)

    = render "sign_up/oauth_links"

    = simple_form_for create_session_path,
      html: { class: 'form-horizontal'} do |f|
      %fieldset
        = f.input :email, label: t(:email), as: 'email'
        = f.input :password, label: t(:password), as: 'password'
      .form-actions
        = f.submit t(:sign_in), class: 'btn btn-primary'
        = edit_button_tag 'Forgot Password?', forgot_password_path
.row
  %p &nbsp;