config/routes.rb
# -*- encoding : utf-8 -*-
#
Yarb::Application.routes.draw do

  root 'landings#index'

  match 'set_locale/:locale' => 'application#set_locale',      via: 'GET',  as: 'set_locale'

  match 'sign_in'            => 'session#new',                 via: 'GET',  as: 'sign_in'
  match 'sign_in'            => 'session#create',              via: 'POST', as: 'create_session'
  match 'sign_out'           => 'session#delete',              via: 'GET',  as: 'sign_out'
  match 'forgot_password'    => 'session#forgot_password',     via: 'GET',  as: 'forgot_password'
  match 'reset_password'     => 'session#reset_password',      via: 'POST', as: 'reset_password'

  match 'sign_up'            => 'sign_up#new',                 via: 'GET',  as: 'sign_up'
  match 'sign_ups'           => 'sign_up#create',              via: 'POST', as: 'sign_ups'
  match 'sign_up/accept_invitation/:token' => 'sign_up#accept_invitation', via: 'GET', as: 'accept_sign_up_invitation'

  match '/auth/:provider/callback' => 'session#create',        via: 'GET'
  match '/auth/identity/register'  => 'users#create',          via: 'POST'
  match '/auth/failure'            => 'session#failure',       via: 'GET'
  match '/sign_up/complete_auth'   => 'session#complete_auth', via: 'POST'

  match 'confirm_email/:token' => 'email_confirmation#confirm', via: 'GET', as: 'confirm_email'

  match 'users/:token/edit_password' => 'users#edit_password', via: 'GET', as: 'edit_password_users'
  match 'users/:token/update_password' => 'users#update_password', via: 'POST', as: 'update_password_users'

  resources :users
  resources :sign_up_invitations, only: [:index, :new, :create, :destroy]


  resources :pages do
    collection do
      post 'update_order'
    end
  end

end

app/models/user.rb
# -*- encoding : utf-8 -*-


# The User-class
# * uses BCrypt to encrypt passwords
# * key :id is equal to :email but used parameterized by module Store
class User

  include Persistable
  include Roles

  key_method :id
  attribute  :email, unique: true
  validates_presence_of :email

  attribute  :name
  validates_presence_of :name

  attribute :edit_token

  # @param [Hash] args
  # @option args [String] :name - The username
  # @option args [String] :email - User's email
  def initialize args={}
    set_attributes args
    ensure_authentication
  end

  # Create a user without Identity but with an OAuth-provider
  # @param [Hash] auth OmniAuth authentication-hash
  # @return [User] the user created
  def self.create_from_auth auth
     create_user_with_auth auth
  end

  # Creates a unique id for the user.
  # @return [String]
  def id
    @id ||= "%x-%s" % [ Time.now.to_i, SecureRandom::hex(2) ]
  end

  # ensure we have a valid id and authentication
  def save
    id and ensure_authentication and super
  end

  # Delete Authentications before deleting self
  def delete
    Authentication.where(user_id: id).each { |auth| auth.delete }
    super
  end

  # Returns the User's Authentication object
  # @param [Symbol] provider (default :identity)
  # @return [Authentication]
  def authentication provider=:identity
    Authentication.where(user_id: id, provider: provider).all.first
  end

  # @return [Array] all user's authentications
  def authentications
    Authentication.where(user_id: id).all
  end


  # @return [Array] all user's authentications but local identity
  def oauth_autentications
    self.authentications.reject {|a| a.provider == :identity}
  end

  # Creates a one-time token for editing the User's password, sends out an email with a link
  def create_edit_token!
    self.edit_token = SecureRandom.hex
    save
    UserMailer.password_change_token(email, edit_token).deliver
  end

  def update_password_with_token!(_password, _token)
    raise 'Unvalid Edit Token' unless edit_token == _token
    self.password = _password
    self.edit_token = nil
    save
  end

  # Finds a User by his/her edit_token
  def self.find_by_token(_token)
    User.find_by(:edit_token, _token)
  end

  # Delete an existing authentication (for :identity) and create a new one
  # @param [String|Symbol] provider
  # @param [String] uid - user's id at provider
  # @return [Authentication]
  def recreate_authentication provider, uid
    authentication.delete
    Authentication.create! provider: provider, uid: uid, user_id: id
  end

  # Replace an existing authentication(:identity)
  # @param [Hash] auth - the authentication-hash
  # @option auth [String|Symbol] :provider (eg :identity, 'twitter', ...)
  # @option auth [String|Symbol] :uid - Unique ID for provider
  # @return [User] user with newly created authentication
  def recreate_authentication_with_hash auth
    recreate_authentication auth[:provider], uid: auth[:uid]  unless identity?(auth)
    self
  end

  # @return [Boolean] true if email is marked as confirmed
  def email_confirmed?
    @confirmation = EmailConfirmation.find_by( :user_id, self.id )
    @confirmation && @confirmation.confirmed?
  end

  # @return [Time|String] time of confirmed_at or 'n/a'
  def confirmed_at
    email_confirmed? ? Time.zone.parse(@confirmation.confirmed_at.to_s) : nil
  end

  # @return [Boolean] true if roles matches
  def can_see_foreign_user_information?
    has_any_role?(Roles::SEE_USER_INFORMATION_ROLES)
  end

  # @return [Boolean] true if any authentication but local identity
  def has_oauth_authentications?
    oauth_autentications.any?
  end

  private

  def self.create_user_with_auth auth
    _user = create auth_user_params(auth)
    _user.recreate_authentication_with_hash(auth)
  end

  def self.auth_user_params(auth)
    { name: auth[:info][:name], email: auth[:info][:email] }
  end

  def identity? auth
    auth[:provider] == :identity
  end

  def ensure_authentication
    Authentication.find_by( :user_id, id ) || Authentication.create!(user_id: id)
  end

  # delegate password-methods to Authentication
  delegate "password",               to: :authentication
  delegate "password=",              to: :authentication
  delegate "password_confirmation",  to: :authentication
  delegate "password_confirmation=", to: :authentication
  delegate "authenticate",           to: :authentication
  delegate "old_password",           to: :authentication
  delegate "old_password=",          to: :authentication

  def after_save
    super
    request_confirm_email
    self
  end

  def request_confirm_email
    UserMailer.request_confirm_email(self).deliver if needs_confirmation?
  end

  def needs_confirmation?
    c = EmailConfirmation.find_by(:user_id, self.id)
    if c && c.email != self.email
      c.delete
      true
    elsif c.nil?
      true
    else
      false
    end
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-"

# Show and edit User's profile
class UsersController < ApplicationController

  before_filter :load_resource, except: [:index, :edit_password, :update_password]
  before_filter :authenticate_user, except: [:index, :edit_password, :update_password]
  protect_from_forgery except: [:update_password]
  helper_method :allow_edit_user?

  # GET /users
  def index
    if !current_user.has_role?( :admin )
      redirect_back_or_to root_path, status: 404
    else
      User.expire_selector
      @users = User.asc(:name)
    end
  end

  # GET /users/:id
  def show
  end

  # GET /users/:id/edit
  def edit
  end

  # GET /users/edit_password?token=_token
  def edit_password
    User.expire_selector
    @user = User.find_by_token(params[:token])

    if @user
      @token = @user.edit_token
      @password = @password_confirmation = ''
    else
      redirect_to root_path if @user.nil?
    end

  end

  # POST /users/change_password
  def update_password
    User.expire_selector
    @user = User.find_by_token(params[:token])

    if @user
      if params[:password] != params[:password_confirmation]
        @password = @password_confirmation = ''
        @token = @user.edit_token
        flash[:warn] = 'Passwords did not match'
        render :edit_password
      else
        @user.update_password_with_token!(params[:password], params[:token])
        redirect_to sign_in_path, notice: 'Password changed'
      end
    else
      redirect_to root_path
    end
  end

  # PUT /users/:id
  def update
    if @user.update_attributes( user_update_params ) && change_password
      redirect_to @user, notice: t("user.successfully_updated", email: @user.email)
    else
      render :edit
    end
  end

  # DELETE /users/:id
  def destroy
    @user.delete
    redirect_to users_path, notice: t("user.successfully_deleted", name: @user.name)
  end

  private

  def allow_edit_user? user=NilUser.new
    user.id == current_user.id || current_user.has_role?(:admin)
  end

  def change_password
    ChangePasswordService.new(self, @user, params[:user] ) and @user.save
  end

  def user_update_params
    roles_if_admin.merge({ name: name_param , email: email_param })
  end

  def roles_if_admin
    current_user.has_role?(:admin) ? { roles: roles_param } : {}
  end

  def roles_param
    params[:user].fetch(:roles).reject(&:blank?).map!(&:to_sym).compact
  end

  def name_param
    params[:user].fetch(:name)  { @user.name}
  end

  def email_param
    params[:user].fetch(:email) { @user.email }
  end

  def authenticate_user
    redirect_back_or_to root_path, notice: t(:access_denied) unless allow_edit_user?(@user)
  end

  def load_resource
    User.expire_selector
    @user = User.find( params[:id] )
  end

end

app/helpers/users_helper.rb
# Helper functions for UsersController
module UsersHelper

  # Array of check-box-options for simple_form
  # @return [Array] [[label, value], [label, value],... ]
  def user_role_checkbox_selection
    Roles::ROLES.map{|r| [ t("roles.#{r}"), r] }
  end

end

app/views/users/_form.haml
.gap-top= render_errors_for @user
= simple_form_for @user, html: {class: 'form-horizontal'} do |f|

  = f.input :id, disabled: true, hint: t(:can_not_be_changed)
  = f.input :name, label: t("user.name")
  = f.input :email, label: t("user.email")

  - if @user.authentication(:identity)
    %h4.gap-top= t("user.change_password")
    = f.input :old_password, label: t("user.old_password")
    = f.input :new_password, label: t("user.new_password")
    = f.input :password_confirmation, label: t("user.password_confirmation")

  - if current_user.has_role?( :admin )
    %h4.gap-top= I18n.t("roles.headline")
    = f.input :roles, as: :check_boxes,
      collection: user_role_checkbox_selection,
      label: false, input_html: { class: 'roles-check-boxes' }

  .form-actions
    = f.submit t(:save), class: save_button_classes
    = cancel_button_tag t(:cancel), :back

app/views/users/_user_admin.haml
- if current_user.has_role?(:admin)
  = right_admin_box do
    .btn.btn-default
      = link_to icon_with_text('icon-list', t("user.listing")), users_path
    .btn.btn-default
      - if ApplicationHelper.needs_invitation?
        = link_to icon_with_text('icon-list', t("sign_up.invitation_list")), sign_up_invitations_path
      - else
        = link_to icon_with_text('icon-plus-sign', t("user.new")), sign_up_path

app/views/users/_user_list_entry.haml
- UserPresenter.present(user,self) do |presenter|
  %li{id: "user-#{user.id}"}
    .pull-right
      = presenter.delete_user_link
      = presenter.edit_user_link
    .pull-left
      .gap-right= gravatar_tag(user.email).html_safe
    .user-information
      .name-and-email= presenter.name_and_email
      .email-confirmed-at= presenter.email_confirmed_at if current_user.can_see_foreign_user_information?
      .inline-block.small-subtitle= presenter.user_roles unless user.roles.empty?
      .inline-block.small-subtitle= presenter.authentications if user.has_oauth_authentications?
    .clear-left

app/views/users/edit.haml
.row{id: "edit-user-#{@user.id}"}
  .span6.offset2
    = gravatar_tag(@user.email).html_safe
    %h1= t("user.edit_user_title")
    = render "form", user: @user

app/views/users/edit_password.haml
.row{id: "edit-user-password"}
  .span6.offset2
    %h2= t('user.change_password')
    %form.form-horizontal(action="/users/#{@token}/update_password" method="post")
      .control-group
        %label.control-label= t('password')
        .controls
          %input(type="password" name="password"  style="margin-left: 0px" pattern=".{6,}" required title="6 characters minimum")
      .control-group
        %label.control-label= t('user.password_confirmation')
        .controls
          %input(type="password" name="password_confirmation" style="margin-left: 0px" pattern=".{6,}" required title="6 characters minimum")
      .control-group
        .controls
          %input.btn(type="submit" value="#{t(:save)}" )

app/views/users/index.haml
- if ApplicationHelper.needs_invitation?
  = right_admin_box do
    .btn.btn-default= link_to icon_with_text('icon-list', t("sign_up.invitation_list")), sign_up_invitations_path
    - if ApplicationHelper::needs_invitation?
      = new_button_tag t("sign_up.new_invitation"), new_sign_up_invitation_path

%h1= t("user.index_title")

#user-list
  %ul
    - @users.each do |user|
      = render "user_list_entry", user: user

app/views/users/show.haml
= render "user_admin"

- UserPresenter.present(@user,self) do |presenter|
  = presenter.user_listing_tag do
    %h1= gravatar_tag(@user.email).html_safe
    %h2.small-subtitle= @user.name
    %p.small
      %strong UID:
      =presenter.user_id

    %small
      %strong E-Mail:
      = presenter.user_email
    %hr/
    %p.small-subtitle=presenter.user_roles
    %p.small-subtitle=presenter.authentications