config/routes.rb
# -*- encoding : utf-8 -*-
#
Yarb::Application.routes.draw do

  root 'landings#index'

  match 'set_locale/:locale' => 'application#set_locale',      via: 'GET',  as: 'set_locale'

  match 'sign_in'            => 'session#new',                 via: 'GET',  as: 'sign_in'
  match 'sign_in'            => 'session#create',              via: 'POST', as: 'create_session'
  match 'sign_out'           => 'session#delete',              via: 'GET',  as: 'sign_out'
  match 'forgot_password'    => 'session#forgot_password',     via: 'GET',  as: 'forgot_password'
  match 'reset_password'     => 'session#reset_password',      via: 'POST', as: 'reset_password'

  match 'sign_up'            => 'sign_up#new',                 via: 'GET',  as: 'sign_up'
  match 'sign_ups'           => 'sign_up#create',              via: 'POST', as: 'sign_ups'
  match 'sign_up/accept_invitation/:token' => 'sign_up#accept_invitation', via: 'GET', as: 'accept_sign_up_invitation'

  match '/auth/:provider/callback' => 'session#create',        via: 'GET'
  match '/auth/identity/register'  => 'users#create',          via: 'POST'
  match '/auth/failure'            => 'session#failure',       via: 'GET'
  match '/sign_up/complete_auth'   => 'session#complete_auth', via: 'POST'

  match 'confirm_email/:token' => 'email_confirmation#confirm', via: 'GET', as: 'confirm_email'

  match 'users/:token/edit_password' => 'users#edit_password', via: 'GET', as: 'edit_password_users'
  match 'users/:token/update_password' => 'users#update_password', via: 'POST', as: 'update_password_users'

  resources :users
  resources :sign_up_invitations, only: [:index, :new, :create, :destroy]


  resources :pages do
    collection do
      post 'update_order'
    end
  end

end

app/views/pages/_controller_buttons.haml
- unless current_page?( pages_path )
  = list_button_tag t(:pages), pages_path

app/views/pages/_editor_buttons.haml
- if has_roles? PagesController::PAGE_EDITOR_ROLES
  = edit_button_tag t(:edit), edit_page_path(page)

app/views/pages/_form.haml
= render_errors_for page
= simple_form_for page, html: { class: standard_form_classes } do |f|

  = f.input :title, input_html: { class: 'full-width' }
  = f.input :body, as: :text, input_html: { rows: 15, class: 'full-width' }

  .form-actions
    = f.input :draft, inline_label: t(:draft), as: :boolean, label: t(:save_as_draft)
    = f.submit t(:save), class: save_button_classes
    = cancel_button_tag t(:cancel),  pages_path
    .pull-right= render 'terminator_buttons', page: page

app/views/pages/_page.haml
%li{ id: "page-#{page.to_param}", class: 'list-entry bottom-bordered' }
  .btn-group.pull-right= render "page_edit_buttons", page: page
  = render 'sortable_handles', page: page
  = link_to_unless_current page.title, page_path(page)
  .draft= t(:is_a_draft) if [1, "1", true].include?(page.draft)
  = render "page_information", page: page

app/views/pages/_page_edit_buttons.haml
= render 'editor_buttons', page: page
= render 'terminator_buttons', page: page
= render 'controller_buttons', page: page

app/views/pages/_page_information.haml
.page-information
  = model_date_information(page)

app/views/pages/_sortable_handles.haml
- if has_roles?( PagesController::PAGE_EDITOR_ROLES) && current_page?(pages_path)
  %span.sortable-number-and-icon
    = icon('icon-resize-vertical')
    = "#{(page.position||0).to_s.humanize}.)"

app/views/pages/_terminator_buttons.haml
- unless page.new_record?
  - if has_roles? PagesController::PAGE_TERMINATOR_ROLES
    = delete_link_tag page_path(page), t("delete_page")

app/views/pages/edit.haml
.pull-right
  .btn-group
    = render 'controller_buttons', page: @page

%h1= t(:edit_page)
= render 'form', page: @page

app/views/pages/index.haml
- if has_roles? PagesController::PAGE_CREATOR_ROLES
  .pull-right=new_button_tag t(:add_new_page), new_page_path

%h1=t(:listing_of_pages)

%ul#pages-list{ page_list_css_sort_options }
  = render @pages

app/views/pages/new.haml
.pull-right= list_button_tag t(:pages), pages_path

%h1= t(:add_new_page)

= render 'form', page: @page

app/views/pages/show.haml
.small-page-title.gap-bottom
  = render 'page', page: @page

%article
  = markdown( @page.body ) if @page.body