config/routes.rb
# -*- encoding : utf-8 -*-
#
Yarb::Application.routes.draw do

  root 'landings#index'

  match 'set_locale/:locale' => 'application#set_locale',      via: 'GET',  as: 'set_locale'

  match 'sign_in'            => 'session#new',                 via: 'GET',  as: 'sign_in'
  match 'sign_in'            => 'session#create',              via: 'POST', as: 'create_session'
  match 'sign_out'           => 'session#delete',              via: 'GET',  as: 'sign_out'
  match 'forgot_password'    => 'session#forgot_password',     via: 'GET',  as: 'forgot_password'
  match 'reset_password'     => 'session#reset_password',      via: 'POST', as: 'reset_password'

  match 'sign_up'            => 'sign_up#new',                 via: 'GET',  as: 'sign_up'
  match 'sign_ups'           => 'sign_up#create',              via: 'POST', as: 'sign_ups'
  match 'sign_up/accept_invitation/:token' => 'sign_up#accept_invitation', via: 'GET', as: 'accept_sign_up_invitation'

  match '/auth/:provider/callback' => 'session#create',        via: 'GET'
  match '/auth/identity/register'  => 'users#create',          via: 'POST'
  match '/auth/failure'            => 'session#failure',       via: 'GET'
  match '/sign_up/complete_auth'   => 'session#complete_auth', via: 'POST'

  match 'confirm_email/:token' => 'email_confirmation#confirm', via: 'GET', as: 'confirm_email'

  match 'users/:token/edit_password' => 'users#edit_password', via: 'GET', as: 'edit_password_users'
  match 'users/:token/update_password' => 'users#update_password', via: 'POST', as: 'update_password_users'

  resources :users
  resources :sign_up_invitations, only: [:index, :new, :create, :destroy]


  resources :pages do
    collection do
      post 'update_order'
    end
  end

end

app/models/sign_up_invitation.rb
# -*- encoding : utf-8 -*-"

# If configured in `config/environments/application_:env_settings.rb` a new
# User will need an invitation to sign up.
class SignUpInvitation
  include Persistable

  key_method :token
  attribute :token, :unique => true
  attribute :to,    :unique => true, :email => true
  validates_presence_of   :token
  validates_presence_of   :to

  # @param [User] sender
  # @param [String] receiver (email-address)
  # @param [Hash] options (optional)
  # @option options [String] :subject Subject for the email
  # @option options [String] :message (optional message for the body of the email)
  def initialize sender, receiver, *options
    @sender_id      = sender.id
    @receiver_email = receiver
    @options        = options.first
  end

  # Returns the email's sending User
  # @return [User] the email's sending User
  def sender
    @sender ||= User.find( @sender_id )
  end

  # @return [String] sender's email
  def from
    @from ||= sender.email
  end

  # @return [String] receiver's email
  def to
    @receiver_email
  end

  # The subject of the mail
  # @return [String] (default "Invitation")
  def subject
    @options.fetch(:subject) { "Invitation" }
  end

  # An optional message provided by the sender
  # @return [String]
  def message
    @options.fetch(:message) { "" }
  end

  # A random invitation token
  # @return [String]
  def token
    @token ||= "%x-%s" % [ Time.now.to_i, SecureRandom::hex(4) ]
  end

  # Send the mail
  def deliver
    UserMailer.sign_up_invitation(self).deliver
  end
end

app/controllers/sign_up_invitations_controller.rb
# -*- encoding : utf-8 -*-"

# Send SignUpInvitations
class SignUpInvitationsController < ApplicationController

  before_filter :clear_cache
  before_filter :ensure_admin!

  # GET /sign_up_invitations
  def index
    @sign_up_invitations = SignUpInvitation.all
  end

  # GET /sign_up_invitations/new
  def new
    @sign_up_invitation = build_new_invitation
  end

  # POST /sign_up_invitations
  def create
    @sign_up_invitation = create_invitation
    deliver_valid_invitation(@sign_up_invitation)
  end

  # DELETE /sign_up_invitations/:token
  def destroy
    invitation = SignUpInvitation.find( params[:id] )
    invitation.delete
    redirect_to sign_up_invitations_path, notice: t("sign_up.invitation_rejected")
  end

  private
  def sign_up_params
    receiver = params[:sign_up_invitation][:to]
    message  = params[:sign_up_invitation][:message]
    [receiver, message: message]
  end

  def build_new_invitation
    SignUpInvitation.new(current_user, '', message: '')
  end

  def create_invitation
    invitation = SignUpInvitation.new(current_user, *sign_up_params)
    invitation.save or invitation
  end

  def deliver_valid_invitation(invitation)
    if invitation.valid?
      invitation.deliver
      redirect_to sign_up_invitations_path, notice: t("sign_up.invitation_sent_to", email: invitation.to).html_safe
    else
      render :new
    end
  end

  def ensure_admin!
    redirect_back_or_to root_path, alert: t(:access_denied) unless current_user.has_role?(:admin)
  end

  def clear_cache
    SignUpInvitation.expire_selector
  end

end

app/views/sign_up_invitations/index.haml
= right_admin_box do
  - if ApplicationHelper::needs_invitation?
    = new_button_tag t("sign_up.new_invitation"), new_sign_up_invitation_path
  = list_button_tag t("users"), users_path

%h1=t("sign_up.sent_invitations_list")

%table.table
  %thead
    %th{colspan: 2} From
    %th{colspan: 2} To
    %th Token
    %th{colspan: 2} Message
  %tbody.table
  - @sign_up_invitations.each do |invitation|
    %tr
      %td.avatar= invitation.sender ? gravatar_tag(invitation.from).html_safe : ""
      %td= invitation.sender ? invitation.sender.email : "n/a"
      %td.avatar= invitation.to ? gravatar_tag(invitation.to).html_safe : ""
      %td= invitation.to ? invitation.to : "n/a"
      %td= invitation.token
      %td
        %span{ title: invitation.message }
          = invitation.message.truncate(120,ommit: '...')
      %td.buttons= delete_link_tag sign_up_invitation_path(invitation), t("sign_up.delete_invitation")

app/views/sign_up_invitations/new.haml
= right_admin_box do
  = list_button_tag t(:users), users_path
  = list_button_tag t("sign_up.invitations"), sign_up_invitations_path

%h1= t("sign_up.new_sign_up_invitation")

.alert.alert-info= t("sign_up.send_invitation_help")

= simple_form_for @sign_up_invitation, html: {class: standard_form_classes}  do |f|
  .fieldset
    = f.input :to, input_html: { class: "full-width" }, as: :email, placeholder: "your@friend.com"
    = f.input :message, as: :text, class: "full-width", input_html: { class: "full-width", rows: 10 }
  .form-actions
    = f.submit deliver_button(t("sign_up.send_invitation")), class: save_button_classes
    = cancel_button_tag t(:cancel), :back